#
# Build:
# docker build -f Dockerfile.frontend -t frontend .
#
# Run:
# docker run -d -p 5000:5000 frontend
#

FROM node:14

WORKDIR /usr/src/app

COPY ./example-frontend/ .

RUN npm install \
    && npm install -g serve \
    && npm run build \
    && useradd -m appuser \ 
    && rm -rf src \
    && rm -rf node_modules  

ENV REACT_APP_BACKEND_URL=http://localhost:8080

USER appuser

EXPOSE 5000

CMD serve -s -l 5000 build

