######
#
# Building:
# $ docker build . -t curler
#
# Running:
# $ docker run -it curler
#
# Output:
# Input website:
# helsinki.fi
# Searching..
# <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
# <html><head>
# <title>301 Moved Permanently</title>
# </head><body>
# <h1>Moved Permanently</h1>
# <p>The document has moved <a href="https://www.helsinki.fi/">here</a>.</p>
# </body></html>
#
######

FROM ubuntu:18.04

COPY website.sh .

RUN apt update && apt install -y curl

CMD ./website.sh
