#
# Build:
# docker build -t backend -f Dockerfile.backend . 
#
# Run:
# docker run -d -p 8080:8080 backend
#

FROM golang:alpine3.14 as build-stage

WORKDIR /usr/src/app

COPY ./example-backend/ .

RUN go build  


#FROM golang:alpine3.14
FROM alpine:3.14

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/server .

RUN adduser -D appuser 

USER appuser

EXPOSE 8080

ENV GIN_MODE=release

CMD ./server

