version: '3.5'

services:

   kumo-front:
      build:
         context: ./ml-kurkkumopo-frontend/
         dockerfile: Dockerfile
      container_name: kumo-frontend
      ports:
         - 3000:3000

   kumo-back:
      build:
         context: ./ml-kurkkumopo-backend/
         dockerfile: Dockerfile
      container_name: kumo-backend
      ports:
         - 5000:5000
      depends_on:
         - kumo-training
      volumes:
         - model:/src/model 

   kumo-training:
      build:
         context: ./ml-kurkkumopo-training/
         dockerfile: Dockerfile
      container_name: kumo-training
      volumes:
         - model:/src/model
         - imgs:/src/imgs

volumes:
   model:
   imgs:
