version: '3.5'

services:

   redis-composed:
      image: library/redis
      container_name: redis-composed
      command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

   backend-composed:
      build: 
         context: . 
         dockerfile: Dockerfile.backend
      container_name: backend-composed
      ports:
         - 8080:8080
      environment:
         REDIS_HOST: redis-composed
         REQUEST_ORIGIN: http://localhost:5000

   frontend-composed:
      build: 
         context: ../../part1/1.14.Environment
         dockerfile: Dockerfile.frontend
      container_name: frontend-composed
      ports:
         - 5000:5000
