version: '3.5'

services:

   db:
      image: postgres:14-alpine
      restart: unless-stopped
      environment:
         POSTGRES_PASSWORD: exercise
      container_name: db
      volumes:
         - ./database:/var/lib/postgresql/data

   nginx:
      image: nginx:1.19-alpine
      volumes:
         - ../../part2/2.8/nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
         - 80:80
      environment:
         NGINX_HOST: localhost
         NGINX_PORT: 80

   backend-composed:
      build: 
         context: ../../part2/2.4/ 
         dockerfile: ../../part3/3.6.frontend_and_3.7.backend/Dockerfile.backend-multi
      container_name: backend-composed
      ports:
         - 8080:8080
      environment:
         REQUEST_ORIGIN: http://localhost
         REDIS_HOST: redis-composed
         POSTGRES_HOST: db
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: exercise 
         POSTGRES_DATABASE: postgres
      depends_on:
         - db

   frontend-composed:
      build: 
         context: ../../part1/1.14.Environment
         dockerfile: ../../part3/3.6.frontend_and_3.7.backend/Dockerfile.frontend-multi
      container_name: frontend-composed
      ports:
         - 5000:5000

   redis-composed:
      image: library/redis
      container_name: redis-composed
      command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

